name: /data5/taomingyu_5/conda_envs/parallel_ai_feynman
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.7.22
  - cloudpickle=3.1.2
  - cpython=3.10.21
  - gmp=6.3.0
  - gmpy2=2.3.1
  - icu=78.3
  - joblib=1.6.0
  - ld_impl_linux-64=2.46.1
  - libblas=3.11.0
  - libcblas=3.11.0
  - libffi=3.7.0
  - libgcc=16.2.0
  - libgcc-ng=16.2.0
  - libgfortran=16.2.0
  - libgfortran-ng=16.2.0
  - libgfortran5=16.2.0
  - libgomp=16.2.0
  - liblapack=3.11.0
  - liblzma=5.8.3
  - liblzma-devel=5.8.3
  - libnsl=2.0.1
  - libopenblas=0.3.34
  - libsqlite=3.53.4
  - libstdcxx=16.2.0
  - libstdcxx-ng=16.2.0
  - libuuid=2.42.4
  - libxcrypt=4.4.38
  - libzlib=1.3.2
  - mpc=1.4.0
  - mpfr=4.2.2
  - mpmath=1.3.0
  - ncurses=6.6
  - numpy=1.26.4
  - openssl=3.6.4
  - packaging=26.3
  - pandas=2.2.3
  - pip=26.2.1
  - python=3.10.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2026.3
  - python_abi=3.10
  - pytz=2026.3.post1
  - readline=8.3
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - six=1.17.0
  - sympy=1.13.3
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tzdata=2026c
  - xz=5.8.3
  - xz-gpl-tools=5.8.3
  - xz-tools=5.8.3
  - zstd=1.5.7
  - pip:
      - aifeynman==2.0.7
      - contourpy==1.3.2
      - cycler==0.12.1
      - dill==0.4.1
      - filelock==3.32.3
      - fonttools==4.65.0
      - fsspec==2026.7.0
      - jinja2==3.1.6
      - kiwisolver==1.5.1
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - multiprocess==0.70.19
      - networkx==3.4.2
      - pathos==0.3.5
      - pillow==12.3.0
      - pox==0.3.7
      - ppft==1.7.8
      - progress==1.6.1
      - pyparsing==3.3.3
      - seaborn==0.13.2
      - setuptools==59.8.0
      - sklearn==0.0.post12
      - sortedcontainers==2.4.0
      - torch==2.2.2+cpu
      - torchvision==0.17.2+cpu
      - typing-extensions==4.16.0
      - wheel==0.45.1
